-- INITIALIZING DATABASE

CREATE DATABASE projects;

USE projects;

-- DATA CLEANING

SELECT Date, STR_TO_DATE(Date, '%Y-%m-%d') FROM sales LIMIT 10;

UPDATE sales SET Date = STR_TO_DATE(Date, '%Y-%m-%d');

ALTER TABLE sales MODIFY COLUMN Date DATE;

ALTER TABLE sales
	RENAME COLUMN `Transaction ID` to id,
	RENAME COLUMN Date to date,
	RENAME COLUMN `Product Category` to category,
    RENAME COLUMN `Product Name` to product_name,
    RENAME COLUMN `Units Sold` to units_sold,
	RENAME COLUMN `Unit Price` to unit_price,
    RENAME COLUMN `Total Revenue` to total_revenue,
    RENAME COLUMN Region to region,
    RENAME COLUMN `Payment Method` to payment_method;
    
-- DATA ANALYSIS

-- revenue generated by category
SELECT category, ROUND(SUM(total_revenue), 2) AS revenue_by_category FROM sales GROUP BY category;

-- revenue monthly
SELECT DATE_FORMAT(date, '%b') AS month, ROUND(SUM(total_revenue), 2) AS revenue_by_month FROM sales GROUP BY month;

-- net revenue
SELECT ROUND(SUM(total_revenue), 2) AS sales_till_date FROM sales;

-- revenue by region
SELECT region, ROUND(SUM(total_revenue), 2) AS sales_by_region FROM sales GROUP BY region ORDER BY sales_by_region DESC;

-- sales
SELECT region, payment_method, ROUND(SUM(total_revenue), 2) AS revenue FROM sales GROUP BY region, payment_method ORDER BY region;

-- top 3 sales by region
WITH
ProductRevenue AS (
    SELECT region, product_name, SUM(total_revenue) AS revenue FROM sales GROUP BY region, product_name),
RankedProducts AS (
    SELECT region, product_name, revenue, ROW_NUMBER() OVER(PARTITION BY region ORDER BY revenue DESC) AS ranked FROM ProductRevenue)
SELECT region, product_name, revenue FROM RankedProducts WHERE ranked <= 3 ORDER BY region, ranked;
